#!/usr/bin/env bash

# Color files
PFILE="$HOME/.config/polybar/colors.ini"
RFILE="$HOME/.config/rofi/colors.rasi"

# Image
IMAGE="$(find /usr/share/backgrounds -type f | shuf -n 1)"

# Get colors
pywal_get() {
	wal -i "$IMAGE" -q -t
}

# Change colors
change_color() {
	# polybar
	sed -i -e "s/background = #.*/background = $BG/g" $PFILE
	sed -i -e "s/foreground = #.*/foreground = $FG/g" $PFILE
	sed -i -e "s/foreground-alt = #.*/foreground-alt = $FGA/g" $PFILE
	sed -i -e "s/shade1 = #.*/shade1 = $SH1/g" $PFILE
	sed -i -e "s/shade2 = #.*/shade2 = $SH2/g" $PFILE
	sed -i -e "s/shade3 = #.*/shade3 = $SH3/g" $PFILE
	sed -i -e "s/shade4 = #.*/shade4 = $SH4/g" $PFILE
	sed -i -e "s/shade5 = #.*/shade5 = $SH5/g" $PFILE
	sed -i -e "s/shade6 = #.*/shade6 = $SH6/g" $PFILE
	sed -i -e "s/shade7 = #.*/shade7 = $SH7/g" $PFILE
	sed -i -e "s/shade8 = #.*/shade8 = $SH8/g" $PFILE
	
	# rofi
	cat > $RFILE <<- EOF
	/* colors */

	* {
	  al:    #00000000;
	  bg:    ${BG}FF;
	  bg1:   ${SH2}FF;
	  bg2:   ${SH3}FF;
	  bg3:   ${SH4}FF;
	  fg:    ${FG}FF;
	}
	EOF
	
	polybar-msg cmd restart
}

# Main
if [[ -f "/usr/bin/wal" ]]; then
	if [[ "$1" ]]; then
		IMAGE="$1"
	fi

	feh --bg-fill "$IMAGE"
	pywal_get "$IMAGE"

	# Source the pywal color file
	. "$HOME/.cache/wal/colors.sh"

	BG=`printf "%s\n" "$background"`
	FG=`printf "%s\n" "$foreground"`
	FGA=`printf "%s\n" "$foreground"`
	SH1=`printf "%s\n" "$color1"`
	SH2=`printf "%s\n" "$color2"`
	SH3=`printf "%s\n" "$color1"`
	SH4=`printf "%s\n" "$color2"`
	SH5=`printf "%s\n" "$color1"`
	SH6=`printf "%s\n" "$color2"`
	SH7=`printf "%s\n" "$color1"`
	SH8=`printf "%s\n" "$color7"`

	change_color
else
	echo "[!] 'pywal' is not installed."
fi
