#!/bin/bash

# Files

monitors=$(xrandr --query | grep -w connected | awk '{print $1}')

$HOME/.screenlayout/$(xrandr --query | grep -w connected | awk '{print $1}' | tr '\n' '-' | sed 's/\(.*\)-/\1/')

bspc wm -r
