#! /bin/sh
# Code stolen from https://github.com/safinsingh/dots/blob/master/home/.config/bspwm/bspwmrc

_c() { bspc config "$@"; }
_m() { bspc monitor "$@"; }
_s() {
  pkill -x "$1"
  {
    sleep 0.1
    "$@" &
  }
}

# monitors
monitors=($(xrandr --query | grep -w connected | awk '{print $1}'))

#_m ${monitors}

_m eDP -d I II III IV V
_m DisplayPort-2 -d VI VII VIII IX X
#_m -d I II III IV V VI VII VIII IX X 

# config
_c border_width 0
_c window_gap 8
_c borderless_monocle true
_c gapless_monocle true

# pywal colors
. "${HOME}/.cache/wal/colors.sh"

_c normal_border_color "$color1"
_c active_border_color "$color2"
_c focused_border_color "$color15"
_c presel_feedback_color "$color1"

# startup
_s sxhkd
_s picom -b
#_s openrazer-daemon -r
#_s razer-cli -a

for m in ${monitors[@]}; do
    MONITOR=$m polybar --reload main &
done

echo "bspwm ready!"

